http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  user:
    host: localhost
    paths: ['/users','/users/*']
  cliente:
    host: localhost
    paths: ['/cliente','/cliente/*'] 
  restaurante:
    host: localhost
    paths: ['/restaurante','/restaurante/*']
  repartidor:
    host: localhost
    paths: ['/repartidor','/repartidor/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  userService:
    url: 'http://localhost:3000'
  clienteService:
    url: 'http://localhost:4000'
  restauranteService:
    url: 'http://localhost:5000'
  repartidorService:
    url: 'http://localhost:6000'   
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: userService 
              changeOrigin: true
  clientePipeline:
    apiEndpoints:
      - cliente
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: clienteService 
              changeOrigin: true
  restaurantePipeline:
    apiEndpoints:
      - restaurante
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: restauranteService 
              changeOrigin: true
  repartidorPipeline:
    apiEndpoints:
      - repartidor
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: repartidorService 
              changeOrigin: true
